name: VirtualViewProductions
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14148
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a6a7ab'
    - '#6d6e70'
    - '#cdced0'
    - '#292728'
  brandStrength: 0.5
  lightness: 0.6686037709005177
  saturation: 0.375
  rhythmicContrast: 0.5000294104684144
purpose: []
