name: VirtualViewProductions
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14148
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0f2c56'
    - '#62625a'
    - '#818388'
    - '#a0a6a9'
  brandStrength: 0.5
  lightness: 0.6686037709005177
  saturation: 0.375
  rhythmicContrast: 0.5000294104684144
purpose: []
